server:
  port: 8080


spring:
  application:
    name:

# DataSource Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/project_db # or 3306
    username: root # or user
    password: 12345

  # Thymeleaf Cache Setting
  thymeleaf:
      cache: false
      suffix: .html
      prefix: classpath:/templates/


  # JPA Setting
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    access:
      claim-key: logined
      expires-at: 7200
      token-type: Bearer
    refresh:
      claim-key: refresh
      expires-at: 2592000
      token-type: Basic
    authorization-header: Authorization
  password:
    encode:
      algorithm: PBKDF2WithHmacSHA1
      iterations: ${AUTH_ITERATIONS}
      keyLength: ${KEY_LENGTH}